### ISSUE TITLE
Error when release package-win

### ISSUE THREAD

**Issue by rahmatkruniawan** [amilajack/erb-sqlite-example#1]
@amilajack  When run in dev mode, it's fine. But when I try to release package-win. I got some error. Did something miss ?

> Error: read ECONNRESET
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:569:26)
From previous event:
    at D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\src\packager\dirPackager.ts:51:7
    at next (native)
From previous event:
    at unpack (D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\out\packager\dirPackager.js:37:21)
    at unpackElectron (D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\src\packager\dirPackager.ts:36:10)
    at D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\src\platformPackager.ts:156:22
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at WinPackager.doPack (D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\out\platformPackager.js:272:11)
    at D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\src\platformPackager.ts:101:16
    at next (native)
From previous event:
    at WinPackager.pack (D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\out\platformPackager.js:169:11)
    at D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\src\packager.ts:257:24
    at next (native)
    at xfs.mkdir.er (D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager.doBuild (D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\out\packager.js:379:11)
    at D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\src\packager.ts:170:52
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\out\packager.js:274:11)
    at D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\src\builder.ts:198:33
    at next (native)
From previous event:
    at build (D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (D:\belajar\facebookReactJS\electron\testSqlite\erb-sqlite-example\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by amilajack** [comment]
[Try packaging to linux using docker](https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build)

**Comment by rahmatkruniawan** [comment]
@amilajack  I release for win it's working but do not use npm but yarg.
But can u gift me clue for redirect path react router in programatically 
*PS : thanks, for fast response

**Comment by amilajack** [comment]
> but do not use npm but yarg

So using yarn works for you but npm doesn't?

**Comment by amilajack** [comment]
Closing due to no response 😢

**Comment by rahmatkruniawan** [comment]
@amilajack Sry I got some busy time 😄

**Comment by amilajack** [comment]
Did you resolve this?

**Comment by rahmatkruniawan** [comment]
@amilajack  yeah. resolved. Thabks btw 😄
